import { CREDIT_CARDS, PRICE_TABLES, PRODUCT_CARD, PROFILE_CARD, QR_CODE_COMPONENT, RESPONSIVE_HERO } from './challenges/html-css';

import {
  ADVANCED_PASSWORD_GENERATOR,
  BLACK_PLATE,
  FORM_VALIDATE,
  GUESS_THE_NUMBER,
  MEMORY_GAME,
  SIMPLE_PASSWORD_GENERATOR
} from './challenges/javascript';

export const HTML_CSS_CHALLENGES = [QR_CODE_COMPONENT, PROFILE_CARD, CREDIT_CARDS, PRODUCT_CARD, PRICE_TABLES, RESPONSIVE_HERO];

export const JAVASCRIPT_CHALLENGES = [
  GUESS_THE_NUMBER,
  SIMPLE_PASSWORD_GENERATOR,
  MEMORY_GAME,
  FORM_VALIDATE,
  ADVANCED_PASSWORD_GENERATOR,
  BLACK_PLATE
];

export const ALL_CHALLENGES = [
  QR_CODE_COMPONENT,
  PROFILE_CARD,
  CREDIT_CARDS,
  PRODUCT_CARD,
  PRICE_TABLES,
  RESPONSIVE_HERO,
  GUESS_THE_NUMBER,
  SIMPLE_PASSWORD_GENERATOR,
  MEMORY_GAME,
  FORM_VALIDATE,
  ADVANCED_PASSWORD_GENERATOR,
  BLACK_PLATE
];
