import Provider from '@/context/Provider';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Regular y Bold
  style: ['normal', 'italic'], // Normal e Italic para Medium
  variable: '--font-poppins'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <Provider>
      <html lang='en'>
        <body className={poppins.variable}>{children}</body>
      </html>
    </Provider>
  );
}
